Feature "Herramientas de desarrollo"
devs-arg/faq pull request #18
Opened 2023-10-01 22:56 UTC by Nicol4sDev

Me tomé la libertad de agregar un apartado mas, "Herramientas de desarrollo" donde se especifica sobre los software mas comunes que utilizamos a la hora de desarrollar, tanto IDEs, como editores de texto, Gestion de base de datos, etc.

2023-10-02 02:37 UTC, catrielmuller requested changes

2023-10-02 02:37 UTC, catrielmuller commented on package.json
> +    "@napi-rs/simple-git-darwin-arm64": "^0.1.9",
Esto no deberia estar agregado ya que es una dependencia exclusiva de ARM64 que no es usado por el repo y puede traer problemas con el CI

2023-10-02 02:41 UTC, Nicol4sDev commented on package.json
> +    "@napi-rs/simple-git-darwin-arm64": "^0.1.9",
Upale, perdon cato, tuve que instalar eso para que me ejecute el npm run. Listo, desinstalado!

2023-10-02 03:03 UTC, catrielmuller approved these changes

2023-10-02 03:03 UTC, merged

2023-10-03 23:15 UTC, Gdakgdak22 approved these changes